In [1]:
# Import the required libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report

In [2]:
# Load the dataset
df = pd.read_csv('Iris - Iris.csv')

# Display the first 5 rows to verify the data
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
# Load the dataset
df = pd.read_csv('Iris - Iris.csv')

# Display the first 5 rows to verify the data
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
# The 'Id' column is not useful for prediction, so we drop it
df = df.drop('Id', axis=1)

# Separate features (X) and target/labels (y)
X = df.drop('Species', axis=1)
y = df['Species']

# Split the data into Training and Testing sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"Training data shape: {X_train.shape}")
print(f"Testing data shape: {X_test.shape}")

Training data shape: (105, 4)
Testing data shape: (45, 4)

In [7]:
# 1. Implement Simple Naive Bayes classification algorithm
# Initialize the Gaussian Naive Bayes classifier
nb_model = GaussianNB()

# Train the model using the training data
nb_model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = nb_model.predict(X_test)

In [8]:
# 2. Compute Confusion matrix
# Since there are 3 species, this will be a 3x3 matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]

In [9]:
# Compute TP, FP, TN, FN for each class
# TP is the diagonal elements
TP = np.diag(cm)

# FP is the sum of the respective column minus the TP
FP = cm.sum(axis=0) - TP

# FN is the sum of the respective row minus the TP
FN = cm.sum(axis=1) - TP

# TN is the total sum of the matrix minus (TP + FP + FN)
TN = cm.sum() - (FP + FN + TP)

# Mapping the values to their respective class names
classes = nb_model.classes_

for i in range(len(classes)):
    print(f"Metrics for Class: {classes[i]}")
    print(f" True Positives (TP): {TP[i]}")
    print(f" False Positives (FP): {FP[i]}")
    print(f" False Negatives (FN): {FN[i]}")
    print(f" True Negatives (TN): {TN[i]}\n")

Metrics for Class: Iris-setosa
 True Positives (TP): 19
 False Positives (FP): 0
 False Negatives (FN): 0
 True Negatives (TN): 26

Metrics for Class: Iris-versicolor
 True Positives (TP): 12
 False Positives (FP): 0
 False Negatives (FN): 1
 True Negatives (TN): 32

Metrics for Class: Iris-virginica
 True Positives (TP): 13
 False Positives (FP): 1
 False Negatives (FN): 0
 True Negatives (TN): 31

In [10]:
# Compute Accuracy, Error rate, Precision, and Recall
# We use 'macro' average to find the unweighted mean for our multi-class data
accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')

print(f"Overall Accuracy: {accuracy:.4f} (or {accuracy*100:.2f}%)")
print(f"Error Rate: {error_rate:.4f} (or {error_rate*100:.2f}%)")
print(f"Macro Precision: {precision:.4f}")
print(f"Macro Recall: {recall:.4f}")

Overall Accuracy: 0.9778 (or 97.78%)
Error Rate: 0.0222 (or 2.22%)
Macro Precision: 0.9762
Macro Recall: 0.9744

In [11]:
# Additional: Display full sklearn classification report
print("Classification Report:\n")
print(classification_report(y_test, y_pred))

Classification Report:

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       1.00      0.92      0.96        13
 Iris-virginica       0.93      1.00      0.96        13

       accuracy                           0.98        45
      macro avg       0.98      0.97      0.97        45
   weighted avg       0.98      0.98      0.98        45